-- =========================================================
-- SIPINTAR_MI v10
-- Struktur Database Inti
-- =========================================================

-- 1. DAFTAR GURU / USER
create table if not exists daftar_guru (
    id bigint generated by default as identity primary key,
    username text unique not null,
    password text not null,
    nama_guru text,
    role text not null,
    kelas_diampu text,
    mapel_diampu text,
    no_whatsapp text,
    foto_profil text,
    aktif boolean default true,
    created_at timestamp with time zone default now()
);

-- 2. MASTER SISWA
create table if not exists tabel_master_siswa (
    id bigint generated by default as identity primary key,
    no int,
    nama_siswa text not null,
    nis text,
    nama_ibu text,
    alamat text,
    no_whatsapp text,
    tanggal_lahir date,
    biaya_mobil numeric default 0,
    biaya_lks numeric default 0,
    kelas text,
    aktif boolean default true,
    created_at timestamp with time zone default now()
);

-- 3. MASTER MAPEL
create table if not exists tabel_mapel (
    id bigint generated by default as identity primary key,
    kode_mapel text,
    nama_mapel text not null,
    kelompok_mapel text,
    aktif boolean default true
);

-- 4. KALENDER PENDIDIKAN
create table if not exists tabel_kaldik (
    id bigint generated by default as identity primary key,
    tanggal date not null,
    jenis_hari text,
    keterangan text,
    semester int,
    tahun_ajaran text
);

-- 5. JADWAL INDUK
create table if not exists tabel_jadwal_induk (
    id bigint generated by default as identity primary key,
    hari text not null,
    jam_ke int,
    jam_mulai time,
    jam_selesai time,
    kelas text,
    mapel text,
    guru text,
    semester int,
    tahun_ajaran text
);

-- 6. JADWAL HARIAN
create table if not exists tabel_jadwal_harian (
    id bigint generated by default as identity primary key,
    tanggal date not null,
    hari text,
    jam_ke int,
    jam_mulai time,
    jam_selesai time,
    kelas text,
    mapel text,
    guru text,
    materi text,
    tp text,
    status_kbm text default 'BELUM_DIISI',
    dijadwal_ulang_dari bigint,
    created_at timestamp with time zone default now()
);

-- 7. JURNAL KBM
create table if not exists tabel_jurnal_kbm (
    id bigint generated by default as identity primary key,
    jadwal_harian_id bigint,
    tanggal date,
    guru text,
    kelas text,
    mapel text,
    materi text,
    tp text,
    status_pelaksanaan text,
    catatan_guru text,
    tindak_lanjut text,
    created_at timestamp with time zone default now()
);

-- 8. PR
create table if not exists tabel_pr (
    id bigint generated by default as identity primary key,
    jurnal_kbm_id bigint,
    tanggal date,
    guru text,
    kelas text,
    mapel text,
    isi_pr text,
    batas_pengumpulan date,
    kirim_wa boolean default false,
    created_at timestamp with time zone default now()
);

-- 9. TUGAS
create table if not exists tabel_tugas (
    id bigint generated by default as identity primary key,
    jurnal_kbm_id bigint,
    tanggal date,
    guru text,
    kelas text,
    mapel text,
    isi_tugas text,
    jenis_tugas text,
    batas_pengumpulan date,
    created_at timestamp with time zone default now()
);

-- 10. KOKURIKULER TEMPORER
create table if not exists tabel_kokurikuler (
    id bigint generated by default as identity primary key,
    tanggal date,
    guru text,
    kelas text,
    dimensi_profil_lulusan text,
    panca_cinta text,
    kegiatan text,
    catatan text,
    created_at timestamp with time zone default now()
);