-- =========================================================
-- SIPINTAR_MI v10
-- Struktur Database Keuangan
-- Diadaptasi dari aplikasi bendahara lama
-- =========================================================

-- 1. PEMBAYARAN / IURAN SISWA
create table if not exists tabel_pembayaran_siswa (
    id bigint generated by default as identity primary key,
    siswa_id bigint,
    pos_tagihan text not null,
    nominal numeric default 0,
    tanggal date,
    kelas text,
    keterangan text,
    periode_bulan int,
    periode_tahun int,
    dibuat_oleh text,
    created_at timestamp with time zone default now()
);

-- 2. TABUNGAN SISWA
create table if not exists tabel_tabungan_siswa (
    id bigint generated by default as identity primary key,
    siswa_id bigint,
    jenis text,
    nominal numeric default 0,
    tanggal date,
    kelas text,
    keterangan text,
    dibuat_oleh text,
    created_at timestamp with time zone default now()
);

-- 3. TRANSAKSI BENDAHARA
create table if not exists tabel_transaksi_bendahara (
    id bigint generated by default as identity primary key,
    nama_bendahara text,
    pos_dana text,
    jenis_transaksi text,
    nominal numeric default 0,
    tanggal date,
    keterangan text,
    foto_nota text,
    kelas text,
    sumber_transaksi text,
    dibuat_oleh text,
    created_at timestamp with time zone default now()
);

-- 4. TARGET MANUAL TAGIHAN
create table if not exists tabel_target_manual (
    id bigint generated by default as identity primary key,
    kelas text,
    pos_tagihan text,
    nominal numeric default 0,
    periode_tahun int,
    keterangan text,
    created_at timestamp with time zone default now()
);

-- 5. ABSEN SISWA
create table if not exists tabel_absen_siswa (
    id bigint generated by default as identity primary key,
    siswa_id bigint,
    kelas text,
    tanggal date,
    status text,
    guru_id bigint,
    keterangan text,
    created_at timestamp with time zone default now(),
    unique (siswa_id, tanggal)
);

-- 6. AUDIT LOG KEUANGAN
create table if not exists tabel_audit_log_keuangan (
    id bigint generated by default as identity primary key,
    tabel_sumber text,
    sumber_id bigint,
    aksi text,
    data_lama jsonb,
    data_baru jsonb,
    dilakukan_oleh text,
    waktu timestamp with time zone default now()
);